#! /bin/sh
nvidia-settings --load-config-only &
sxhkd &
~/.config/polybar/launch.sh &
/usr/bin/dunst &
discord &
#picom &
#xcompmgr &
#guake &
iSaX.bin &


feh --bg-fill ~/.config/wall.jpg
bspc monitor DVI-D-0 -d 1 2 3 4 5 6 7 8 9 10
#bspc monitor HDMI-0 -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         10
bspc config window_gap          8
bspc config top_padding                   0
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0

#bspc config split_ratio          0.52
#bspc config borderless_monocle   true
#bspc config gapless_monocle      true

bspc config single_monocle                false
bspc config click_to_focus                false
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#### BSPWM coloring ####
bspc config normal_border_color		      "#e6ecec"
bspc config active_border_color	          "#e6ecec"
bspc config focused_border_color	      "#e6ecec"
bspc config presel_feedback_color	      "#e6ecec"
#bspc config urgent_border_color 	      "#dd2727"


bspc rule -a code-oss desktop='^4' state=fullscreen
